package com.java.hsaalgorithm;

import java.math.BigInteger;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;

public class SHA256Algorithm {

    public static byte[]getSHA(String input) throws NoSuchAlgorithmException{
        MessageDigest md = MessageDigest.getInstance("SHA-256");
        return md.digest(input.getBytes(StandardCharsets.UTF_8));
    }

    public static String toHexString(byte[] hash){
        BigInteger number = new BigInteger(1,hash);
        StringBuilder hexString = new StringBuilder();
        for (byte b : hash) {
            hexString.append(String.format("%02x", b));
        }
        return hexString.toString();
    }

    public static void main(String args[]){
        try{
            System.out.println("HashCode Generated by SHA-265: ");
            String string1 = "String to try";
            System.out.println(string1 + ": " + toHexString(getSHA(string1)));

            String string2 = "hello world";
            System.out.println(string2 + ": " + toHexString(getSHA(string2)));
        }
        catch (NoSuchAlgorithmException e){
            System.out.println("Incorrect algorithm: ");
        }
    }
}

