package com.java.hsaalgorithm;

import java.math.BigInteger;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;

public class SHA256Algorithm {

    public static byte[]getSHA(String input) throws NoSuchAlgorithmException{
        MessageDigest md = MessageDigest.getInstance("SHA-256");
        //Performs a final update on the digest using the specified array of bytes, then completes the digest computation
        return md.digest(input.getBytes());
    }

    public static String hexDecimalString(byte[] hash){
        StringBuilder hexString = new StringBuilder();
        for (byte b : hash) {
            hexString.append(String.format("%02x", b));
        }
        return hexString.toString();
    }

    public static void main(String args[]){
        try{
            System.out.println("HashCode Generated by SHA-265 : ");
            String s = "string to convert";
            System.out.println(s + ": " + hexDecimalString(getSHA(s)));

        }
        catch (NoSuchAlgorithmException e){
            System.out.println("Incorrect algorithm: ");
        }
    }
}

